// Search-result observations + confirmed business fit; no volume/ranking estimates.
const rows = [
  ['codex', 'Codex', 'navigation/#codex', '主词', '观察'],
  ['codex', 'Codex 充值', 'guides/codex-subscription-credits-api/', '计费选择', '重点'],
  ['codex', 'Codex 代充', 'guides/codex-topup-verification/', '开通验收', '重点'],
  ['codex', 'Codex 订阅', 'guides/codex-subscription-credits-api/', '订阅比较', '重点'],
  ['codex', 'Codex 月卡', 'guides/monthly-subscription-renewal/', '期限续费', '跟进'],
  ['codex', 'Codex 独立账号', 'guides/codex-topup-verification/', '账号交付', '跟进'],
  ['gemini', 'Gemini', 'navigation/#gemini', '主词', '观察'],
  ['gemini', 'Gemini 充值', 'guides/gemini-plan-checklist/', '套餐资格', '重点'],
  ['gemini', 'Gemini 代充', 'guides/gemini-topup-account-options/', '交付比较', '重点'],
  ['gemini', 'Google AI Pro 代充', 'guides/gemini-plan-checklist/', '套餐资格', '重点'],
  ['gemini', 'Gemini 独立账号', 'guides/gemini-topup-account-options/', '账号交付', '跟进'],
  ['gemini', 'Gemini 月卡', 'guides/monthly-subscription-renewal/', '期限续费', '跟进'],
  ['grok', 'Grok', 'navigation/#grok', '主词', '观察'],
  ['grok', 'Grok 充值', 'guides/grok-subscription-billing-check/', '计费入口', '重点'],
  ['grok', 'Grok 代充', 'guides/grok-subscription-checklist/', '开通核对', '重点'],
  ['grok', 'SuperGrok 月卡', 'guides/grok-subscription-checklist/', '套餐期限', '重点'],
  ['grok', 'Grok 续费', 'guides/grok-subscription-billing-check/', '账单续费', '跟进'],
  ['grok', 'Grok 独立账号', 'guides/account-topup-or-independent/', '账号交付', '跟进'],
  ['claude', 'Claude', 'navigation/#claude', '主词', '观察'],
  ['claude', 'Claude 充值', 'guides/claude-topup-verification/', '开通验收', '重点'],
  ['claude', 'Claude 代充', 'guides/claude-topup-verification/', '开通验收', '重点'],
  ['claude', 'Claude Pro 代充', 'guides/claude-pro-max-selection/', '套餐选择', '重点'],
  ['claude', 'Claude Max 订阅', 'guides/claude-pro-max-selection/', '套餐选择', '跟进'],
  ['claude', 'Claude 独立账号', 'guides/account-topup-or-independent/', '账号交付', '跟进'],
  ['claude-code', 'Claude Code', 'navigation/#claude-code', '主词', '观察'],
  ['claude-code', 'Claude Code 充值', 'guides/claude-code-subscription-api/', '计费选择', '重点'],
  ['claude-code', 'Claude Code 月卡', 'guides/claude-code-cost-checklist/', '成本比较', '重点'],
  ['claude-code', 'Claude Code 订阅', 'guides/claude-code-subscription-api/', '订阅比较', '重点'],
  ['claude-code', 'Claude Code 额度', 'guides/claude-code-usage-checklist/', '用量排查', '跟进'],
  ['claude-code', 'Claude Code 多少钱', 'guides/claude-code-cost-checklist/', '成本比较', '跟进'],
  ['all', 'AI 代充和独立账号区别', 'guides/account-topup-or-independent/', '交付比较', '跟进'],
  ['all', 'AI 会员月卡续费', 'guides/monthly-subscription-renewal/', '期限续费', '跟进'],
];
export const KEYWORDS = Object.freeze(rows.map(([topic,query,route,intent,priority]) => Object.freeze({topic,query,route,intent,priority})));
