// Distinct buying questions found in public search results. No quoted prices or stock promises.
export const TOPUP_GUIDES = [
  {
    slug: 'codex-topup-verification', service: 'codex', modified: '2026-10-09', title: 'Codex 代充后怎么验收？账号、订阅与用量核对',
    description: 'Codex 代充或独立账号交付后，核对 ChatGPT 登录身份、实际订阅、Codex 用量与有效期，区分未开通、额度限制和登录问题。',
    summary: 'Codex 代充是否完成，要在目标账号中核对订阅和实际用量；付款截图或“充值成功”消息不能替代验收。账号不符、套餐未生效和用量耗尽需要分别处理。',
    sections: [
      { title: '付款前约定验收标准', list: ['写清是给原账号开通订阅，还是交付独立账号。', '写清实际套餐、周期起算方式、总价与交付时间。', '说明购买的是订阅权益、额外使用额度，还是另一种服务。', '约定开通失败、账号不符或延迟交付时如何处理。'] },
      { title: '交付后按三个位置核对', table: { headers: ['核对位置', '要看什么', '能确认的事情'], rows: [['正在登录的账号', '与你约定的账号是否一致', '权益是否开在正确账号'], ['ChatGPT 订阅与账单', '套餐名称、状态和周期', '实际交付的订阅是否符合约定'], ['Codex Settings 或用量面板', '可用权益、余额与重置提示', '当前使用条件是否与你购买的内容一致']] }, paragraphs: ['不要只核对账号昵称或商家截图。自己登录目标账号，在可用的官方页面中查看实际状态，保留不含敏感凭据的验收记录。'] },
      { title: '可以登录，但仍提示额度不足', paragraphs: ['先确认会员是否有效，再查看 Codex 的用量提示。OpenAI 的说明将套餐权益与额外用量分开；部分用量可能与账号中的其他功能共享。', '在支持该命令的 Codex CLI 会话中，可用 /status 查看当前状态；也可检查 Settings 或用量面板。用量耗尽不等于代充未完成，不要在原因不明时重复付费。'] },
      { title: '独立账号还要核对什么', paragraphs: ['确认交付的账号与报价一致、是否包含会员、剩余期限如何计算，以及哪些管理权限按约定移交。独立交付不自动等于新注册账号或完整一个月。', '保存账号归属与售后约定；初次咨询只说明需求，不提供密码、访问令牌、API Key 或验证码。'] },
      { title: '如何说明验收异常', paragraphs: ['向已核实的客服提供产品、约定套餐、交付时间和不含敏感信息的状态说明。例如：“已登录约定账号，订阅页显示的套餐与报价不一致，请核对交付。”', '若套餐正确而工具无法使用，说明是登录、网络、权限还是用量提示。会员付款不能保证解决每一种工具故障。'] },
    ],
    sources: [['Codex 套餐与用量说明', 'https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan']],
    faqs: [['Codex 代充成功后为什么仍不能用？', '可能是登录了其他账号、订阅未按约定生效、用量限制或工具环境问题。先核对身份、订阅和状态提示，再处理对应原因。'], ['Codex 独立账号是否一定有完整月卡期限？', '不一定。要写清是从交付开始计算，还是交付账号已有订阅的剩余期限，并在账号页面核对。']],
    related: ['codex-subscription-credits-api', 'account-topup-or-independent', 'monthly-subscription-renewal'],
  },
  {
    slug: 'gemini-topup-account-options', service: 'gemini', modified: '2026-10-09', title: 'Gemini 代充、独立账号与家庭共享有什么区别？',
    description: '购买 Gemini 或 Google AI Pro 服务前，比较原账号代充、独立账号和家庭共享的权益来源、账号权限、资格与续费，避免混淆交付方式。',
    summary: 'Gemini 代充保留原账号，独立账号涉及账号交付，家庭共享依赖家庭方案的权益。这三种方式不能只用“Gemini 月卡”一个名称概括，需分别核对会员来源与管理权限。',
    sections: [
      { title: '先确认报价对应哪一种交付', table: { headers: ['方式', '账号与权益', '重点核对'], rows: [['原账号代充', '在你已有账号上开通适用方案', '原订阅、账号资格与续费衔接'], ['独立账号', '交付单独使用的账号，会员内容另行约定', '管理权限、套餐和剩余期限'], ['家庭共享', '通过家庭方案获得可共享的权益', '家庭资格、权益范围与成员变更影响']] } },
      { title: 'Google AI Pro 代充先核对资格', paragraphs: ['Google 的订阅说明要求使用符合条件的个人 Google 账号。实际可开通性还要结合账号地区、年龄要求、现有订阅及购买渠道判断。', '如果已有第三方渠道订阅或特殊账号状态，应先在账号的 Google One 页面核对可升级方案，不承诺所有账号都能开通。'] },
      { title: '家庭权益不等于个人完整订阅', paragraphs: ['Google 官方说明中，符合条件的家庭成员可以享有部分 AI 权益。实际范围应按当前方案与成员账号确认，不能把家庭组席位直接表述为每人一份独立个人订阅。', '询问成员资格、可使用功能、原个人订阅是否受影响，以及家庭方案结束或成员变更后如何处理。GetToken 的已知主要交付方式是代充与独立账号，此处比较不表示已经销售家庭共享。'] },
      { title: '验收时查账号，别只看商品名称', list: ['在实际使用账号中确认 Google AI 套餐或权益来源。', '核对需要的 Gemini 功能是否可用，存储空间不代表模型用量。', '确认服务起算时间、到期处理和是否自动续费。', '核对与报价一致的账号控制范围，保留交付与售后约定。'] },
      { title: '续费前问清楚总成本', paragraphs: ['比较同一周期的总价，而不是只看折算月价；确认活动到期后是否换价，以及续费是否保留原账号与权益来源。', '如果原账号资格或方案已经改变，先核实新的可交付条件。不要依据旧截图或其他账号的促销入口直接付款。'] },
    ],
    sources: [['Google AI Pro 订阅资格与家庭权益', 'https://support.google.com/googleone/answer/16476811?hl=zh-Hans']],
    faqs: [['Gemini 成品号就是独立会员吗？', '不一定。要分别确认是否独立交付账号、是否包含个人付费会员、权益是否来自家庭共享，以及可移交的管理权限。'], ['Gemini 年卡一定比月卡划算吗？', '需要同时比较总价、实际有效期、续费条件与售后。首期活动价或剩余期限不能直接当成完整长期订阅的月成本。']],
    related: ['gemini-plan-checklist', 'account-topup-or-independent', 'monthly-subscription-renewal'],
  },
  {
    slug: 'grok-subscription-billing-check', service: 'grok', modified: '2026-10-09', title: 'Grok 充值选哪个入口？SuperGrok、X 与应用商店账单核对',
    description: '开通或续费 Grok 前，核对 SuperGrok、X Premium 和应用商店的账号绑定及账单渠道，排查会员未显示、重复购买和续费问题。',
    summary: 'Grok 充值先确认登录身份和原购买渠道。SuperGrok、X 相关权益与应用商店账单需要按实际账号核对；会员未显示时先查账号绑定，避免重复订阅。',
    sections: [
      { title: '从原来的订单来源开始', table: { headers: ['原购买渠道', '先核对的位置', '处理重点'], rows: [['Grok 网页', 'grok.com 的 Settings → Billing', '实际套餐、账单和续费'], ['Apple App Store', '原 Apple 账号的订阅记录', '原登录方式与商店订阅'], ['Google Play', '原 Google 账号的订阅记录', '订阅账号、周期及取消渠道'], ['X 相关订阅', 'X 套餐与 Grok 的账号关联', '该套餐当前权益及绑定账号']] } },
      { title: '不要把入口差异理解为一定要买两份', paragraphs: ['xAI 官方 FAQ 说明，部分 X 相关订阅权益需要在正确关联的账号中识别。核对正在登录的 Grok 账号，以及需要关联的 X 账号是否一致。', '权益范围可能变化。比较当前套餐与目标账号中的实际显示，而不是直接认为所有 X 套餐都包含相同 Grok 权益，或所有入口都必须独立付款。'] },
      { title: '已付款但网页或 App 没显示会员', paragraphs: ['先确认使用原购买时的登录方式。同一个人在不同入口用不同登录方式，可能实际进入了两个账号；这时重复付款不会修复账号识别问题。', '核对原商店订阅状态和 Grok 当前账号，再把未遮盖敏感信息前的截图处理干净后提供给实际收款方或官方支持。代充订单还需核对约定的交付账号。'] },
      { title: '续费与取消由原账单渠道处理', paragraphs: ['Grok 官方说明按网页、Apple、Google Play 和 X 等来源区分订阅管理渠道。先记录实际扣款方，询问取消续费与退款分别由谁处理。', '取消自动续费与退款是两种操作，不保证取消后自动退回已支付费用。具体处理以原订单渠道、官方规则和与商家的约定为准。'] },
      { title: '代充报价需要包含哪些信息', list: ['实际使用入口、套餐与正确账号。', '开通新周期还是延长现有周期。', '到期时间、是否自动续费及由谁管理。', '实际价格、币种、交付时间和异常处理。'] },
    ],
    sources: [['Grok 官方账户与账单 FAQ', 'https://docs.x.ai/grok/faq']],
    faqs: [['有 X 会员还需要再买 SuperGrok 吗？', '先核对你的具体 X 套餐当前包含的权益和账号关联。不同套餐、时间和账号状态可能不同，不能只凭“X 会员”判断。'], ['Grok 月卡开通后为什么 App 还是免费状态？', '先检查 App 是否使用原购买的账号和登录方式，再核对会员状态及账号绑定；不要直接重复购买。']],
    related: ['grok-subscription-checklist', 'monthly-subscription-renewal', 'account-topup-or-independent'],
  },
  {
    slug: 'claude-topup-verification', service: 'claude', modified: '2026-10-09', title: 'Claude 代充怎么验收？Pro / Max 会员、账单与续费核对',
    description: 'Claude Pro 或 Max 代充后，核对账号、实际套餐、会员周期和账单渠道，排查未生效、用量限制及重复续费。',
    summary: 'Claude 代充完成后，应在约定账号中核对 Pro / Max 套餐和周期。会员有效、当前用量可用与 API 计费是不同检查项，付款凭证不能替代实际权益验证。',
    sections: [
      { title: '报价先写清套餐与操作类型', list: ['Pro 或具体 Max 方案，避免只写“Claude 高级会员”。', '新开通、续费或升级，以及原账号已有订阅如何处理。', '原账号代充或独立账号交付，会员是否包含在价格中。', '服务周期、真实总价、交付和售后条件。'] },
      { title: '交付后核对三项记录', table: { headers: ['记录', '要确认的内容', '常见误会'], rows: [['目标账号', '当前登录身份与约定一致', '在另一账号里查会员'], ['订阅与账单页面', '实际套餐、计费周期和管理渠道', '只有付款截图就认为已开通'], ['当前用量或限制提示', '可用范围、重置提示和额外计费选项', '达到用量限制就当成会员失效']] } },
      { title: '按原购买渠道查看账单', paragraphs: ['Claude 官方账单 FAQ 按网页和应用商店等来源说明管理方式。应使用实际购买渠道查看订阅与凭证；商家代充还要保存双方确认的服务清单。', '不应把商家收据直接当成账号的官方订阅凭证，也不应仅凭看到官方账单就忽略实际账号是否正确。'] },
      { title: '会员还有效，为什么使用受限', paragraphs: ['订阅期限与使用额度是不同维度。先核对当前账号的会员状态和用量提示，再决定等待重置、调整方案或咨询异常处理。', '如果涉及额外用量、API 或套餐附带的独立 API 额度，需要分别看对应说明和计费页面；不能仅用会员月费推断所有入口的剩余额度。'] },
      { title: '续费前怎样避免重复扣款', paragraphs: ['确认原自动续费是否仍开启、由谁管理，以及代充是否会与原计费周期重叠。升级和续费的结算方式可能不同，应先核对实际报价。', '验收异常时提供约定套餐、时间及不含敏感凭据的状态说明。客服未核实前，不发送密码、验证码或恢复码。'] },
    ],
    sources: [['Claude 官方账单 FAQ', 'https://support.claude.com/en/articles/8325618-paid-plan-billing-faqs'], ['Claude 用量与额外计费', 'https://support.claude.com/en/articles/12429409-manage-usage-credits-for-paid-claude-plans']],
    faqs: [['Claude Pro / Max 代充后怎样证明会员已生效？', '在约定账号中核对实际套餐、状态和周期，并与报价清单比较。付款截图只能证明付款记录，不能替代权益核对。'], ['Claude 续费和升级有什么区别？', '续费延长既有服务，升级改变套餐；实际周期、费用抵扣和生效方式需要在原账单渠道及报价中确认。']],
    related: ['claude-pro-max-selection', 'claude-code-subscription-api', 'monthly-subscription-renewal'],
  },
  {
    slug: 'claude-code-cost-checklist', service: 'claude-code', modified: '2026-10-09', title: 'Claude Code 月卡多少钱才划算？订阅与按量总成本核对',
    description: '比较 Claude Code 月卡、Claude 订阅和 API 按量成本，核对额度、计费来源、附加费用与续费，避免只看低月价。',
    summary: 'Claude Code 的成本取决于接入方式、任务消耗和额外收费。比较同一周期、同一使用方式的总成本，先核对计费来源；GetToken 报价未确认前，不给出虚构月卡价格。',
    sections: [
      { title: '先查当前实际按哪条路径计费', paragraphs: ['确认正在用 Claude 订阅账号还是 API 凭据。Claude 官方说明提醒：环境中存在 ANTHROPIC_API_KEY 时，可能改用 API 身份和计费，不能只根据已购买会员判断当前费用。', '只查看自己的配置和工具状态，不把密钥值或完整环境输出发给客服。使用 /status 等当前工具支持的状态入口核对登录和用量，再按对应账单页面确认。'] },
      { title: '把成本分成三部分比较', table: { headers: ['成本项', '需要记录', '比较时的边界'], rows: [['固定周期费用', '真实订阅或月卡总价、有效期', '是否为完整周期，是否含账号'], ['额外使用费用', '超额、附加额度或 API 用量', '是否另行计费、有无预算上限'], ['其他已确认费用', '服务费、续费变化或其他约定', '只计算明确列出的项目']] }, paragraphs: ['同一周期总成本 = 已确认固定费用 + 实际额外用量费用 + 其他已确认费用。这是比较口径，不是价格承诺，也不意味着每个方案都包含全部收费项。'] },
      { title: '为什么不能承诺统一每日消息条数', paragraphs: ['代码库规模、上下文长度、任务复杂度和工具调用会影响消耗。先说明工作类型与遇到限制的频率，记录真实账单或用量，再比较固定方案与按量方式。', '订阅、API 额度和额外用量的规则可能更新。若套餐提供独立 API 额度，要单独核对适用范围；不能假设它抵扣所有 Claude Code 用量。'] },
      { title: '月卡报价至少需要回答这些问题', list: ['是 Claude 订阅登录、API 接入还是第三方服务。', '原账号代充或独立账号，账号控制范围是什么。', '期限、额度、重置规则和超额处理是什么。', '是否有自动充值、预算上限和额外收费。', '续费后是否保留原接入方式，异常与退款如何处理。'] },
      { title: '把实际需求交给客服核价', paragraphs: ['例如：“我在终端做日常项目开发，希望保留自己的账号，先比较一个月订阅与按量费用。请说明登录方式、限制、完整总价和额外收费。”', '比较报价前先确认账号资格与真实可售服务。没有真实套餐和账单数据，就无法断言某个方案一定更便宜。'] },
    ],
    sources: [['Claude Code 订阅与 API 身份说明', 'https://support.claude.com/en/articles/11145838-use-claude-code-with-your-pro-or-max-plan'], ['Max 与 Team 的独立 API 额度说明', 'https://support.claude.com/en/articles/17154008-monthly-api-credits-for-max-and-team-plans']],
    faqs: [['Claude Code 有会员还会产生 API 费用吗？', '可能。先核对实际登录、API 凭据与计费页面，尤其检查是否设置了 ANTHROPIC_API_KEY。会员有效不能代替计费来源检查。'], ['Claude Code 月卡和 API 哪个更便宜？', '要比较同一周期的真实固定费用、实际用量和额外收费。没有任务与账单数据，不能给出对所有人都适用的结论。']],
    related: ['claude-code-subscription-api', 'claude-code-usage-checklist', 'claude-pro-max-selection'],
  },
];
